### PR TITLE
Fix Android Example Link

### PR DESCRIPTION
**Pull request by kaikeru**
* Updates the "Library Example" link to the correct URL

### CODE REVIEW

**Review by hinglau886 — APPROVED** [review]

**Review by lange11 — COMMENTED** [review]
Let u 'no

**Review by lange11 — APPROVED** [review]
- [ ] ANDROID.md

**Comment by casandrariggins** [comment]
Stay out of my cash app

**Comment by casandrariggins** [comment]
Please and thank you

**Review by jitpack-io — APPROVED** [review]

**Comment by jitpack-io** [comment]
Thanks!

**Pull request merged**
